pub const NUM_SERVERS: usize = 1;
pub const GLOBAL_HEAP_START: usize = 0x400000000000 as usize;
pub const UNIT_HEAP_SIZE_GB: usize = 96;
pub const WORKER_HEAP_SIZE: usize = NUM_SERVERS * UNIT_HEAP_SIZE_GB as usize * 1024 * 1024 * 1024; // 48 for GEMM & 16 for all others
pub const WORKER_UNIT_SIZE: usize = WORKER_HEAP_SIZE / NUM_SERVERS;
pub const MAX_SERVERS: usize = 16;
pub static mut SERVER_INDEX: usize = 0;
pub static mut LOCAL_HEAP_START: usize = 0;
pub const RPC_WAIT: u64 = 5000;
pub static mut APPLICATION_NAME: Option<String> = None; // or gemm or kvstore or socialnet